[package]
name = "web_socket_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_json = "1.0.119"
chrono = { version = "0.4.38", features = ["serde"] }
rocket = "0.5.1"
rocket_ws = "0.1.1"
rand = "0.8.5"
